## Numpy (BASICS)

In [1]:
import numpy as np

In [2]:
a = np.array([
    [1,2,3],
    [2,4,6]
])
a.shape

(2, 3)

#### Restrictions
1) All elements of the array must be of the same type of data.
2) Once created, the total size of the array can't change.

In [3]:
# column is at the last and row is at the second last
a[1,1] 

np.int64(4)

1) 0-D -> Scaler
2) 1-D -> Vector
3) 2-D -> Matrix
4) N-D -> Tensors

#### Array attributes

##### ndim, shape, size, dtype

In [6]:
# The number of dimensions of an array is contained in the ndim attribute
a.ndim

2

In [8]:
# The shape of an array is a tupple of non-negative integers that specify the number of elements along each dimension.
a.shape

(2, 3)

In [9]:
# The fixed, total number of elements in array is contained in the size attribute.
a.size

6

In [10]:
# Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. The data type is recorded in the dtype attribute.
a.dtype

dtype('int64')

#### Basic Array Methods
##### np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()

In [15]:
# Creating an array filled with zeroes
b = np.zeros(4)
b

array([0., 0., 0., 0.])

In [22]:
# Creating an array filled wih one's
print(np.ones(3))
print(np.ones(3, dtype=np.int64))

[1. 1. 1.]
[1 1 1]


In [17]:
# Creating an array with empty elements
d = np.empty(2)
d

array([2.00000000e+000, 6.33167929e-310])

In [20]:
# creating an array with a range of elements
print(np.arange(4)) # 0-3 (start, stop, step)
print(np.arange(2,6,2))

[0 1 2 3]
[2 4]


In [21]:
# Create an array with values that are spaced linearly in a specified interval
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])